### ISSUE TITLE
Square Image as input fail - crop_width error in skimage

### ISSUE THREAD

**Issue by tjhenry** [BimBim134/Vibe#1]
Does the input image need to be in a certain format or is this simply a package problem?

Main error seems to be `ValueError: crop_width has an invalid length: 4`

```
> $ ./vibe.py -tx -i timschool.png timprep.png                                                                                                        ⬡ 14.17.3 [±main ●●]
Traceback (most recent call last):
  File "/System/Volumes/Data/DevProjects/experiment/Vibe/./vibe.py", line 389, in <module>
    image = loadPicture(sys.argv[3])
  File "/System/Volumes/Data/DevProjects/experiment/Vibe/./vibe.py", line 65, in loadPicture
    image = crop(image, squareCropCoordinate(image))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/util/arraycrop.py", line 51, in crop
    raise ValueError(
ValueError: crop_width has an invalid length: 4
crop_width should be a sequence of N pairs, a single pair, or a single integer

tim@Tim-Hs-iMac /DevProjects/experiment/Vibe                                                                                                                    [18:07:13]
> $ file timschool.png                                                                                                                                ⬡ 14.17.3 [±main ●●]
timschool.png: PNG image data, 200 x 200, 8-bit/color RGBA, non-interlaced


> $ pip install -r requirements.txt                                                                                                                   ⬡ 14.17.3 [±main ●●]
Requirement already satisfied: scikit-image==0.19.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.19.2)
Requirement already satisfied: numpy==1.21.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.21.5)
Requirement already satisfied: scipy==1.8.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: scikit-commpy==0.7.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: SoundFile==0.10.3.post1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.10.3.post1)
Requirement already satisfied: imageio>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (2.19.2)
Requirement already satisfied: tifffile>=2019.7.26 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (2022.5.4)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (20.8)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (9.1.1)
Requirement already satisfied: PyWavelets>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: networkx>=2.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-image==0.19.2->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-commpy==0.7.0->-r requirements.txt (line 4)) (3.5.2)
Requirement already satisfied: sympy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-commpy==0.7.0->-r requirements.txt (line 4)) (1.10.1)
Requirement already satisfied: cffi>=1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from SoundFile==0.10.3.post1->-r requirements.txt (line 5)) (1.14.5)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cffi>=1.0->SoundFile==0.10.3.post1->-r requirements.txt (line 5)) (2.20)
Requirement already satisfied: pyparsing>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from packaging>=20.0->scikit-image==0.19.2->-r requirements.txt (line 1)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (4.33.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from matplotlib->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (2.8.1)
Requirement already satisfied: mpmath>=0.19 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from sympy->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (1.2.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->scikit-commpy==0.7.0->-r requirements.txt (line 4)) (1.15.0)
```

**Comment by tjhenry** [comment]
Update: This only occurs with already square images.  A non-square image converted successfully.
